name: Assign Issue to Project
on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.0
        with:
          project-url: "https://github.com/users/ptrumpis/projects/3"
          github-token: ${{ secrets.GITHUB_TOKEN }}
